ALTER TABLE cad_ite ADD COLUMN DES_CD1 VARCHAR(18) NULL;
ALTER TABLE cad_ite ADD COLUMN DES_CD2 VARCHAR(18) NULL;
ALTER TABLE cad_ite ADD COLUMN COD_SEC VARCHAR(2) NULL;
UPDATE cad_ite SET DES_CD1 = '', DES_CD2='', COD_SEC='';
UPDATE cad_ite SET DES_ITE = '' WHERE DES_ITE IS NULL AND sql_deleted = 'F';